// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkvJihBBZwSafbna2wRUSnhevYi9TVAM',
    appId: '1:805810301112:web:86bf6a7d6abe05a7116c4d',
    messagingSenderId: '805810301112',
    projectId: 'pr2-25-app-farmacia',
    authDomain: 'pr2-25-app-farmacia.firebaseapp.com',
    storageBucket: 'pr2-25-app-farmacia.firebasestorage.app',
    measurementId: 'G-ZRT9Z09J0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYiziXa7T4mn2tpprn1QtqnSksNjw6wA',
    appId: '1:805810301112:android:51f8801ff06b111c116c4d',
    messagingSenderId: '805810301112',
    projectId: 'pr2-25-app-farmacia',
    storageBucket: 'pr2-25-app-farmacia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtd4MDkEcaUt3LO-jEaVmS1NIcT7BN_dc',
    appId: '1:805810301112:ios:f32c88dc8fe8ce75116c4d',
    messagingSenderId: '805810301112',
    projectId: 'pr2-25-app-farmacia',
    storageBucket: 'pr2-25-app-farmacia.firebasestorage.app',
    iosBundleId: 'com.example.appFarmacia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtd4MDkEcaUt3LO-jEaVmS1NIcT7BN_dc',
    appId: '1:805810301112:ios:f32c88dc8fe8ce75116c4d',
    messagingSenderId: '805810301112',
    projectId: 'pr2-25-app-farmacia',
    storageBucket: 'pr2-25-app-farmacia.firebasestorage.app',
    iosBundleId: 'com.example.appFarmacia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHkvJihBBZwSafbna2wRUSnhevYi9TVAM',
    appId: '1:805810301112:web:fe368a36e04c2e05116c4d',
    messagingSenderId: '805810301112',
    projectId: 'pr2-25-app-farmacia',
    authDomain: 'pr2-25-app-farmacia.firebaseapp.com',
    storageBucket: 'pr2-25-app-farmacia.firebasestorage.app',
    measurementId: 'G-GTVG18J7DE',
  );
}
